apiVersion: v1
kind: Secret
metadata:
  name: environment-variables
  namespace: charts
type: Opaque
stringData:
  db-name: historical
  db-user: postgres
  db-password: postgres
  websocket-url: "ws://192.168.1.138:25520/v1/events"
  base-url: "http://192.168.1.138:25503/v3"
  
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: environment-variables
#   namespace: charts
# data:
#   db-host: "192.168.1.87"
#   db-port: "5432"
#   websocket-url: "ws://192.168.1.138:25520/v1/events"